import { library, config } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import type { IconDefinition } from '@fortawesome/fontawesome-svg-core'

// Prevenir auto-replace de CSS e ícones no SSR
config.autoAddCss = false
config.autoReplaceSvg = false
import { 
  faHome,
  faUsers,
  faBuilding,
  faChartBar,
  faFileAlt,
  faCog,
  faSignOutAlt,
  faUser,
  faBell,
  faLifeRing,
  faBars,
  faTimes,
  faExclamationTriangle,
  faTimesCircle,
  faInfoCircle,
  faCheckCircle,
  faRobot,
  faQuestionCircle,
  faShoppingCart,
  faUtensils,
  faEdit,
  faTrash,
  faChevronDown,
  faChevronRight,
  faBoxOpen,
  faFolderOpen,
  faPlus,
  faLayerGroup,
  faDollarSign,
  faEllipsisH,
  faPizzaSlice,
  faHamburger,
  faCoffee,
  faWineGlass,
  faIceCream,
  faBreadSlice,
  faFish,
  faCheese,
  faAppleAlt,
  faSeedling,
  faBirthdayCake,
  faCloudUploadAlt,
  faSave,
  faSearch,
  faPhone,
  faDownload,
  faFilePdf,
  faSpinner,
  faFileExcel,
  faPrint,
  faCheck,
  faHistory,
  faEye,
  faEyeSlash,
  faTicket,
  faCalendar,
  faClock,
  faCopy,
  faGear,
  faFloppyDisk,
  faUserCog,
  faUserPlus,
  faUserShield,
  faUserTie,
  faHeadset,
  faMotorcycle,
  faCrown,
  faBan,
  faEllipsisVertical,
  faLock,
  faPaperPlane,
  faAddressCard,
  faChartLine,
  faComment
} from '@fortawesome/free-solid-svg-icons'

// Importar ícones de marca (brands)
import {
  faWhatsapp
} from '@fortawesome/free-brands-svg-icons'

// Adicionar todos os ícones à biblioteca
library.add(
  faHome,
  faUsers,
  faBuilding,
  faChartBar,
  faFileAlt,
  faCog,
  faSignOutAlt,
  faUser,
  faBell,
  faLifeRing,
  faBars,
  faTimes,
  faExclamationTriangle,
  faTimesCircle,
  faInfoCircle,
  faCheckCircle,
  faRobot,
  faQuestionCircle,
  faShoppingCart,
  faUtensils,
  faEdit,
  faTrash,
  faChevronDown,
  faChevronRight,
  faBoxOpen,
  faFolderOpen,
  faPlus,
  faLayerGroup,
  faDollarSign,
  faEllipsisH,
  faPizzaSlice,
  faHamburger,
  faCoffee,
  faWineGlass,
  faIceCream,
  faBreadSlice,
  faFish,
  faCheese,
  faAppleAlt,
  faSeedling,
  faBirthdayCake,
  faCloudUploadAlt,
  faSave,
  faSearch,
  faPhone,
  faDownload,
  faFilePdf,
  faSpinner,
  faFileExcel,
  faPrint,
  faCheck,
  faHistory,
  faEye,
  faEyeSlash,
  faTicket,
  faCalendar,
  faClock,
  faCopy,
  faGear,
  faFloppyDisk,
  faUserCog,
  faUserPlus,
  faUserShield,
  faUserTie,
  faHeadset,
  faMotorcycle,
  faCrown,
  faBan,
  faEllipsisVertical,
  faLock,
  faPaperPlane,
  faAddressCard,
  faChartLine,
  faComment,
  faWhatsapp as IconDefinition
)

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.component('FontAwesomeIcon', FontAwesomeIcon)
  nuxtApp.vueApp.component('font-awesome-icon', FontAwesomeIcon)
})
